apiVersion: apps/v1
kind: Deployment
metadata:
  name: dndevops-identity
  namespace: dndevops
  labels:
    app: dndevops-identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dndevops-identity
  template:
    metadata:
      labels:
        app: dndevops-identity
    spec:
      containers:
        - name: dndevops-identity
          image: ghcr.io/roguebit2002/dndevops:0.0.2-dev
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "200m"
              memory: "200Mi"
            limit:
              cpu: "400m"
              memory: "600Mi"
          env:
            - name: DNDEVOPS_DEPLOYMENT
              value: identity
            - name: DNDEVOPS_ADMINS
              value: admin@dndevops.dev
            - name: DNDEVOPS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: USER
            - name: DNDEVOPS_SMTP_URI
              value: smtp://user:password@smtp-service:25
            - name: DNDEVOPS_SMTP_SENDER
              value: dndevops@company.com
            - name: DNDEVOPS_AMQP_URI
              value: amqp://user:password@amqp-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pg-login
                  key: USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: pg-login
                  key: PASSWORD
            - name: DNDEVOPS_IDENTITY_POSTGRES_URI
              value: postgres://$(DB_USER):$(DB_PASS)@dndevops-demo-db.postgres.database.azure.com/dndevops-identity
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dndevops-identity-hpa
  namespace: dndevops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dndevops-identity
    namespace: dndevops
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: dndevops-identity-service
  namespace: dndevops
spec:
  selector:
    app: dndevops-identity
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: "http"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dndevops-identity-ingress
  namespace: dndevops
spec:
  ingressClassName: nginx
  rules:
    - host: dndevops.laurens.me
      http:
        paths:
          - path: /api/identity
            pathType: Prefix
            backend:
              service:
                name: dndevops-identity-service
                port:
                  number: 8000