apiVersion: v1
data:
  SECRET: ENC[AES256_GCM,data:usTJ8dB3WHORoqbA,iv:mTr4U+ciFQyIQUgYQcTaSEKXvUfk83cYPrvW1471LLo=,tag:mPHd2fzZDS0uQ0K5Um6i1w==,type:str]
kind: Secret
metadata:
  name: jwt-secret
  namespace: dndevops
sops:
  age:
    - recipient: age19vsak44nzqfuevtnwn5e0ll4krc96ysrxf9emt984gr46dpn89ss9zy0sy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6RzNNdmdaVjdYZVA5MTEz
        SWZxU1RpOFdPaVR1cFk5SEhrTkJrMnBPaVZzCkNINlJqSnBKN2hMRjVmdmdza2wy
        SW9IQjdqNTZCR3pKRjdOSFJFR3BXUXMKLS0tIDd5bkF5eUJROGxVYlRYUUt0NThV
        djZVZHpNS1VLc1pURFNjQUhNUHllZjAKv79uJYBkofoVafXAPMA2d/DHfRh3dS7f
        NXQtzZWripPM+ZCtD1FeYel7C03FoKYf8p7sUvVXOpQG0R/qZyyQKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T23:55:26Z"
  mac: ENC[AES256_GCM,data:sna/Yr0qM8xvzy2NCP6yedd5FtGPqMox+m/UfQjT5hkaIYwZnuEnhbZf1uvK6pslpL5y9h9VsIG2qD8mkcNUU5i/OGBuNMtcCQ1KT/r+9owAOsbKJBUoKXqm78gskNoJ73g6AviOXzyeFzbkCjb8QqJ7qOfROAw1jO8PMHIwsYg=,iv:rNW+MI9FnGtWaFFheKic5DqssMskDoEw85OHG3DFxa4=,tag:mmyt26AxaL4FSWlKBCpLVA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
