apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - dndevops-identity.yaml
  - dndevops-game.yaml
  - dndevops-events.yaml
  - dndevops-frontend.yaml
  - amqp.yaml
  - smtp.yaml
  - smtp-login.yaml
  - pg-login.yaml